#!/usr/bin/env bash
#
# Regenerate the nginx trusted-proxy list from Cloudflare's published ranges.
#
# Behind Cloudflare, every request arrives from a Cloudflare address. Without
# this, `$remote_addr` IS that address: the gateway's rate limiter (3 req/sec
# per IP) would put every visitor in the world into a handful of buckets and
# start throttling them against each other, and the audit log would record
# Cloudflare as the actor for every action.
#
# `real_ip_header CF-Connecting-IP` is only trustworthy because
# `set_real_ip_from` restricts it to connections that genuinely come FROM
# Cloudflare. Trusting that header from anywhere would let anyone forge their
# own client IP and walk past the rate limiter.
#
# Cloudflare changes these ranges rarely, but it does change them. Run from
# cron; the file is only replaced if the new one is sane and nginx accepts it.
set -euo pipefail

OUT=/etc/nginx/cloudflare-realip.conf
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by infra/refresh-cloudflare-ips.sh — do not edit by hand."
  echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  for u in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    # awk, not `while read`: a final line with no trailing newline is silently
    # dropped by read, and Cloudflare's v6 list ends without one — two ranges
    # went missing that way, which would have left those visitors' real IP
    # unrecovered and sharing one rate-limit bucket.
    curl -fsS --max-time 20 "$u" | awk 'NF {print "set_real_ip_from " $0 ";"}'
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

# A truncated download would silently narrow the trusted set and break real
# client IPs, so refuse anything that does not look like the full list.
lines=$(grep -c '^set_real_ip_from' "$TMP" || echo 0)
if [ "$lines" -lt 20 ]; then
  echo "Only $lines ranges fetched — refusing to replace $OUT" >&2
  exit 1
fi

# Compare ignoring the generated-at comment, so a monthly cron does not reload
# nginx for ten unrelated sites every month just to rewrite a timestamp.
if [ -f "$OUT" ] && diff -q <(grep -v '^# Generated:' "$OUT") <(grep -v '^# Generated:' "$TMP") >/dev/null 2>&1; then
  echo "cloudflare-realip.conf already current ($lines ranges)"
  exit 0
fi

cp -f "$TMP" "$OUT"
if nginx -t >/dev/null 2>&1; then
  systemctl reload nginx
  echo "cloudflare-realip.conf updated: $lines ranges, nginx reloaded"
else
  echo "nginx rejected the new config — check $OUT" >&2
  exit 1
fi
