export { RecentTasks, type RecentTask } from "./recent-tasks"
export { ManagementContacts } from "./management-contacts"
export { WorkerAvatar, type WorkerAvatarProps, type WorkerStatus } from "./worker-avatar"
export { PersonNode, type PersonNodeProps, type PersonNodeTag, type TagVariant } from "./person-node"
export { WorkspaceBox, WORKSPACE_CARD, workspaceCardCols, previewMembers, type WorkspaceBoxProps } from "./workspace-box"
export { WorkspaceGrid, sortWorkspaceBoxes, type WorkspaceGridProps } from "./workspace-grid"
export { ActivityPanel, type ActivityPanelProps, type LiveEvent, type PendingAction } from "./activity-panel"
export { EmployeeDetailPanel, type EmployeeDetailPanelProps } from "./employee-detail-panel"
