/**
 * Demo data for the personnel file.
 *
 *   npx tsx prisma/seed-documents.ts                    (the biggest organization)
 *   npx tsx prisma/seed-documents.ts john@johngroup.com  (a specific one)
 *   npx tsx prisma/seed-documents.ts "John Group"
 *   npx tsx prisma/seed-documents.ts --all               (every organization)
 *
 * Run from apps/api/auth-service.
 *
 * Everything it creates is REAL: the PDFs are rendered and uploaded to whatever
 * object store the service is configured against, so documents genuinely open
 * rather than 404ing on a row that points at nothing. Locally that means MinIO;
 * the script does not care which.
 *
 * Re-runnable. Everything it writes is tagged `demo:` in the storage key or
 * carries a `SEED_` id prefix, and a re-run deletes only its own rows — never a
 * document somebody actually issued.
 */
import { PrismaClient } from '@prisma/client';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { createHash } from 'node:crypto';
import {
  S3Client,
  PutObjectCommand,
  CreateBucketCommand,
  HeadBucketCommand,
} from '@aws-sdk/client-s3';

const prisma = new PrismaClient();

const SEED = 'SEED_DOC_';
const sha256 = (b: Buffer) => createHash('sha256').update(b).digest('hex');

// ── Object storage ───────────────────────────────────────────────────────────

const s3 = new S3Client({
  endpoint: process.env.S3_ENDPOINT ?? 'http://localhost:9000',
  region: process.env.S3_REGION ?? 'us-east-1',
  credentials: {
    accessKeyId: process.env.S3_ACCESS_KEY ?? 'hbcfield',
    secretAccessKey: process.env.S3_SECRET_KEY ?? 'hbcfield-dev-secret',
  },
  forcePathStyle: true,
});
const BUCKET = process.env.S3_BUCKET ?? 'hbcfield';

async function ensureBucket() {
  try {
    await s3.send(new HeadBucketCommand({ Bucket: BUCKET }));
  } catch {
    await s3.send(new CreateBucketCommand({ Bucket: BUCKET }));
    console.log(`  created bucket ${BUCKET}`);
  }
}

/** Store bytes under their own hash, exactly as the service does. */
async function put(orgId: string, bytes: Buffer): Promise<{ key: string; hash: string }> {
  const hash = sha256(bytes);
  const key = `${orgId}/documents/${hash.slice(0, 2)}/${hash}.pdf`;
  await s3.send(
    new PutObjectCommand({ Bucket: BUCKET, Key: key, Body: bytes, ContentType: 'application/pdf' }),
  );
  return { key, hash };
}

// ── A readable one-page PDF ──────────────────────────────────────────────────

/**
 * Rendered rather than faked.
 *
 * A placeholder byte string would list fine and then open as a broken file,
 * which is exactly the half-working demo that hides real problems.
 */
async function makePdf(title: string, lines: string[], accent = false): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({
    x: 0, y: 761, width: 595.28, height: 81,
    color: accent ? rgb(0.145, 0.388, 0.921) : rgb(0.96, 0.97, 0.99),
  });
  page.drawText('HBCField', {
    x: 56, y: 800, size: 11, font: bold,
    color: accent ? rgb(1, 1, 1) : rgb(0.42, 0.48, 0.58),
  });
  page.drawText(title, {
    x: 56, y: 776, size: 18, font: bold,
    color: accent ? rgb(1, 1, 1) : rgb(0.06, 0.09, 0.15),
  });

  let y = 710;
  for (const line of lines) {
    const isHeading = line.startsWith('§') || line.endsWith(':');
    page.drawText(line, {
      x: 56, y, size: isHeading ? 11.5 : 10.5,
      font: isHeading ? bold : regular,
      color: rgb(0.06, 0.09, 0.15),
    });
    y -= isHeading ? 22 : 16;
  }

  page.drawText('Demo document — generated by seed-documents.ts', {
    x: 56, y: 60, size: 8, font: regular, color: rgb(0.62, 0.66, 0.72),
  });
  pdf.setTitle(title);
  pdf.setCreationDate(new Date(Date.UTC(2000, 0, 1)));
  pdf.setModificationDate(new Date(Date.UTC(2000, 0, 1)));
  return Buffer.from(await pdf.save({ useObjectStreams: false }));
}

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const money = (n: number) => `EUR ${n.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
const daysFromNow = (d: number) => new Date(Date.now() + d * 86_400_000);

// ── The seed ─────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n── Personnel file demo data ──\n');
  await ensureBucket();

  /*
    Which organization to fill.

    Pass one as an argument — an admin's email, or part of the organization's
    name — otherwise the BIGGEST one is used.

    Size, not age. This first picked the oldest organization with an admin, which
    on a developer database is a long-abandoned test org: the seed reported 141
    documents and the screen showed nothing, because the person looking was
    logged into the organization they actually work in. Headcount is the honest
    proxy for "the one in use".
  */
  const wanted = process.argv[2]?.trim();
  const candidates = await prisma.organization.findMany({
    where: {
      users: { some: { role: 'ADMIN' } },
      ...(wanted
        ? {
            OR: [
              { name: { contains: wanted, mode: 'insensitive' } },
              { users: { some: { email: { equals: wanted, mode: 'insensitive' } } } },
            ],
          }
        : {}),
    },
    include: { _count: { select: { users: true } } },
  });

  if (candidates.length === 0) {
    throw new Error(
      wanted
        ? `No organization matches "${wanted}". Pass an admin email or part of the name.`
        : 'No organization with an admin. Run the main seed first.',
    );
  }

  const org = candidates.sort((a, b) => b._count.users - a._count.users)[0]!;

  if (!wanted && candidates.length > 1) {
    const others = candidates
      .filter((c) => c.id !== org.id)
      .sort((a, b) => b._count.users - a._count.users)
      .slice(0, 4)
      .map((c) => `${c.name} (${c._count.users})`)
      .join(', ');
    console.log(`  (largest of ${candidates.length}; others: ${others})`);
    console.log('  pass an admin email or org name to choose a different one\n');
  }

  const admin = await prisma.user.findFirst({
    where: { organizationId: org.id, role: 'ADMIN' },
    orderBy: { createdAt: 'asc' },
  });
  if (!admin) throw new Error('That organization has no admin.');

  /*
    The ADMIN is included, and first.

    They were excluded on the first pass — "members get documents, admins issue
    them" — which meant the person most likely to open /my/documents to see
    whether any of this works found "Nothing here yet". An admin is also an
    employee: they have a contract and get paid.
  */
  const others = await prisma.user.findMany({
    where: { organizationId: org.id, isActive: true, role: { not: 'ADMIN' } },
    orderBy: { firstName: 'asc' },
    take: 7,
  });
  const members = [admin, ...others].slice(0, 8);
  if (members.length === 0) throw new Error('That organization has no active users.');

  console.log(`  organization : ${org.name}`);
  console.log(`  admin        : ${admin.email}`);
  console.log(`  files for    : ${members.map((m) => m.firstName).join(', ')}\n`);

  // ── Clear the previous run ────────────────────────────────────────────────
  /*
    Clears its own rows AND anything left behind by hand-testing against this
    database — the same keys under their un-prefixed names. A demo that shows
    "Payslip" twice looks like a bug in the product.
  */
  const priorTypes = await prisma.documentType.findMany({
    where: {
      organizationId: org.id,
      OR: [
        { key: { startsWith: 'demo_' } },
        { key: { in: ['payslip', 'employment_contract', 'gas_safe', 'annual_statement'] } },
      ],
    },
    select: { id: true },
  });
  if (priorTypes.length) {
    const ids = priorTypes.map((t) => t.id);
    // Order matters: events and signatures hang off documents, and documents
    // hold a RESTRICT reference to their type.
    const docs = await prisma.document.findMany({ where: { typeId: { in: ids } }, select: { id: true } });
    const docIds = docs.map((d) => d.id);
    await prisma.documentEvent.deleteMany({ where: { documentId: { in: docIds } } });
    await prisma.documentSignature.deleteMany({ where: { documentId: { in: docIds } } });
    await prisma.document.deleteMany({ where: { id: { in: docIds } } });
    await prisma.documentTemplate.deleteMany({ where: { typeId: { in: ids } } });
    await prisma.documentType.deleteMany({ where: { id: { in: ids } } });
    console.log(`  cleared ${docIds.length} document(s) from a previous run\n`);
  }

  // ── The add-on, or none of this is reachable ──────────────────────────────
  if (!org.addOns.includes('documents')) {
    await prisma.organization.update({
      where: { id: org.id },
      data: { addOns: { push: 'documents' } },
    });
    console.log('  + granted the `documents` add-on\n');
  }

  // Contracts need an employer address and the member a job title, or issuing
  // refuses — which is correct, and worth having the demo data satisfy.
  if (!org.addressLine1) {
    await prisma.organization.update({
      where: { id: org.id },
      data: {
        addressLine1: 'Arbeiterheimstraße 32', city: 'Laakirchen',
        postalCode: '4663', country: 'AT',
      },
    });
    console.log('  + filled in the organization address\n');
  }

  // ── Document types ────────────────────────────────────────────────────────
  const type = async (data: Parameters<typeof prisma.documentType.create>[0]['data']) =>
    prisma.documentType.create({ data: { ...data, organizationId: org.id } });

  const payslip = await type({
    key: 'demo_payslip', label: 'Payslip', cadence: 'MONTHLY', direction: 'ISSUED',
    retentionMonths: 84, signatureMode: 'NONE', position: 0,
    description: 'Monthly pay statement',
  });
  const annual = await type({
    key: 'demo_annual_statement', label: 'Annual statement', cadence: 'ANNUAL',
    direction: 'ISSUED', retentionMonths: 120, signatureMode: 'NONE', position: 1,
  });
  const contract = await type({
    key: 'demo_employment_contract', label: 'Employment contract', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 360, signatureMode: 'IN_APP', position: 2,
  });
  const policy = await type({
    key: 'demo_safety_policy', label: 'Safety policy', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 60, signatureMode: 'ACKNOWLEDGE', position: 3,
  });
  /*
    The rest of what an employer actually asks people to sign.

    One of each MODE, so every path through the signing flow is reachable
    without editing the database:
      IN_APP      draw a signature, seal, certificate
      ACKNOWLEDGE "I have read this" — receipt, no drawing
      WET_INK     the app REFUSES, which was previously only provable in a test
  */
  const nda = await type({
    key: 'demo_confidentiality', label: 'Confidentiality agreement', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 120, signatureMode: 'IN_APP', position: 3,
    description: 'Signed once, on joining',
  });
  const equipment = await type({
    key: 'demo_equipment_handover', label: 'Equipment handover', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 60, signatureMode: 'IN_APP', position: 4,
    description: 'Van, tools and devices issued to a member',
  });
  const amendment = await type({
    key: 'demo_contract_amendment', label: 'Contract amendment', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 360, signatureMode: 'IN_APP', position: 5,
  });
  const conduct = await type({
    key: 'demo_code_of_conduct', label: 'Code of conduct', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 60, signatureMode: 'ACKNOWLEDGE', position: 6,
  });
  const privacy = await type({
    key: 'demo_privacy_notice', label: 'Privacy notice', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 60, signatureMode: 'ACKNOWLEDGE', position: 7,
  });
  const fixedTerm = await type({
    key: 'demo_fixed_term', label: 'Fixed-term contract', cadence: 'ONE_OFF',
    direction: 'ISSUED', retentionMonths: 360, signatureMode: 'WET_INK', position: 8,
  });

  const licence = await type({
    key: 'demo_driving_licence', label: 'Driving licence', cadence: 'ONE_OFF',
    direction: 'SUPPLIED', signatureMode: 'NONE', isCredential: true, hasExpiry: true, position: 4,
    // A card, photographed on both sides: the categories and the
    // machine-readable data are on the back.
    scanShape: 'CARD', twoSided: true,
  });

  /*
    A passport, because it is the document the scanning path is really for.

    Its data page is ID-3 — 125 x 88 mm, not the 85.6 x 54 of a card — and
    everything is on that one page. Seeding it as a card would have the scanner
    draw the wrong frame, which makes the machine-readable zone smaller in the
    photograph and the read worse.
  */
  await type({
    key: 'demo_passport', label: 'Passport', cadence: 'ONE_OFF',
    direction: 'SUPPLIED', signatureMode: 'NONE', isCredential: true, hasExpiry: true, position: 6,
    scanShape: 'PASSPORT', twoSided: false,
  });
  /*
    This one GATES a task type, which is the whole point of the feature: an
    expired certificate has to remove somebody from the assignable pool, and a
    demo where nothing is gated shows "blocks: false" on every row.

    Bound to whichever workflow the organization actually has — a hard-coded id
    would gate nothing on anybody else's database.
    */
  const gatedWorkflow = await prisma.statusWorkflow.findFirst({
    where: { organizationId: org.id },
    orderBy: { createdAt: 'asc' },
    select: { id: true, name: true },
  });
  const gasSafe = await type({
    key: 'demo_gas_safe', label: 'Gas Safe certificate', cadence: 'ONE_OFF',
    direction: 'SUPPLIED', signatureMode: 'NONE', isCredential: true, hasExpiry: true, position: 5,
    requiredForWorkflowIds: gatedWorkflow ? [gatedWorkflow.id] : [],
    // A sheet of A4, not a card, and nothing on the reverse.
    scanShape: 'PAGE', twoSided: false,
  });
  if (gatedWorkflow) {
    console.log(`  Gas Safe gates the "${gatedWorkflow.name}" task type`);
  }
  console.log('  12 document types');

  // ── A contract template ───────────────────────────────────────────────────
  await prisma.documentTemplate.create({
    data: {
      organizationId: org.id, typeId: contract.id,
      name: 'Employment contract — standard',
      signatureMode: 'IN_APP', offerValidDays: 14,
      body: [
        '§1 Position',
        '',
        'The employee {{member.fullName}} is engaged as {{member.jobTitle}} by {{org.legalName}}, {{org.address}}, commencing {{contract.startDate}}.',
        '',
        '§2 Working time',
        '',
        'Regular weekly working time is {{contract.weeklyHours}} hours, distributed Monday to Friday according to the agreed rota.',
        '',
        '§3 Notice',
        '',
        'Either party may terminate this agreement in accordance with the statutory notice periods.',
        '',
        'Issued on {{contract.issuedOn}}.',
      ].join('\n'),
    },
  });
  console.log('  1 contract template');

  // ── Documents ─────────────────────────────────────────────────────────────
  let created = 0;
  const now = new Date();

  const file = async (data: {
    user: (typeof members)[number];
    typeId: string;
    title: string;
    bytes: Buffer;
    periodYear?: number;
    periodMonth?: number;
    status?: 'ISSUED' | 'AWAITING_SIGNATURE' | 'SIGNED' | 'EXPIRED';
    expiresOn?: Date;
    issuedAt?: Date;
    /** null leaves it unread, which is what drives the blue dot. */
    firstOpenedAt?: Date | null;
  }) => {
    const { key, hash } = await put(org.id, data.bytes);
    const issuedAt = data.issuedAt ?? now;
    const doc = await prisma.document.create({
      data: {
        organizationId: org.id,
        userId: data.user.id,
        typeId: data.typeId,
        title: data.title,
        periodYear: data.periodYear ?? null,
        periodMonth: data.periodMonth ?? null,
        storageKey: key,
        sha256: hash,
        sizeBytes: data.bytes.length,
        mimeType: 'application/pdf',
        status: data.status ?? 'ISSUED',
        issuedById: admin.id,
        issuedAt,
        deliveredAt: issuedAt,
        firstOpenedAt: data.firstOpenedAt === undefined ? issuedAt : data.firstOpenedAt,
        expiresOn: data.expiresOn ?? null,
        retentionUntil: null,
      },
    });
    await prisma.documentEvent.create({
      data: { documentId: doc.id, type: 'ISSUED', actorId: admin.id, at: issuedAt },
    });
    created++;
    return doc;
  };

  // Payslips — this year to date, plus all of last year, for everyone.
  const thisYear = now.getFullYear();
  for (const m of members) {
    const monthly = 2400 + (m.firstName.charCodeAt(0) % 9) * 130;
    for (const [year, upto] of [[thisYear, now.getMonth() + 1], [thisYear - 1, 12]] as const) {
      for (let month = 1; month <= upto; month++) {
        const gross = monthly + (month % 3 === 0 ? 180 : 0);
        const bytes = await makePdf(`Payslip — ${MONTHS[month - 1]} ${year}`, [
          `Employee: ${m.firstName} ${m.lastName}`,
          `Period: ${MONTHS[month - 1]} ${year}`,
          '',
          'Earnings:',
          `  Base salary                    ${money(gross)}`,
          `  Overtime                       ${money(month % 3 === 0 ? 180 : 0)}`,
          '',
          'Deductions:',
          `  Income tax                     ${money(gross * 0.32)}`,
          `  Social insurance               ${money(gross * 0.181)}`,
          '',
          `Net pay                          ${money(gross * 0.499)}`,
        ]);
        await file({
          user: m, typeId: payslip.id, title: `Payslip ${MONTHS[month - 1]} ${year}`,
          bytes, periodYear: year, periodMonth: month,
          issuedAt: new Date(year, month - 1, 25),
          // The two most recent are unread, so the blue dot is visible.
          firstOpenedAt: year === thisYear && month >= now.getMonth() ? null : new Date(year, month - 1, 27),
        });
      }
    }

    // Annual statement for last year.
    await file({
      user: m, typeId: annual.id, title: `Annual statement ${thisYear - 1}`,
      periodYear: thisYear - 1,
      issuedAt: new Date(thisYear, 0, 31),
      bytes: await makePdf(`Annual statement ${thisYear - 1}`, [
        `Employee: ${m.firstName} ${m.lastName}`,
        `Tax year: ${thisYear - 1}`,
        '',
        'Summary:',
        `  Gross earnings                 ${money(monthly * 12)}`,
        `  Tax paid                       ${money(monthly * 12 * 0.32)}`,
        `  Social insurance               ${money(monthly * 12 * 0.181)}`,
      ]),
    });
  }

  // A safety policy for everyone — one acknowledged, the rest waiting.
  const policyBytes = await makePdf('Safety policy', [
    'Personal protective equipment:',
    '  Hard hat, eye protection and steel-toed boots on every site.',
    '',
    'Working at height:',
    '  Harness above two metres. No exceptions, and no lone working.',
    '',
    'Reporting:',
    '  Every incident, however minor, on the day it happens.',
  ], true);
  for (const [i, m] of members.entries()) {
    await file({
      user: m, typeId: policy.id, title: 'Safety policy 2026', bytes: policyBytes,
      status: i === 0 ? 'ISSUED' : 'AWAITING_SIGNATURE',
      firstOpenedAt: i === 0 ? now : null,
      issuedAt: daysFromNow(-9),
    });
  }

  /*
    Contracts.

    members[0] (the admin) has a signed one; members[1] gets BOTH — a prior-year
    contract already signed and sealed, and a current one waiting. That is a
    realistic renewal, and it means ONE account shows every state a document can
    be in: signed, waiting, read, and a credential at each standing. Without it
    the only signed contract belongs to the admin, and testing the member
    experience on a phone shows half the picture.
  */
  for (const [i, m] of members.slice(0, 2).entries()) {
    const bytes = await makePdf('Employment contract', [
      '§1 Position',
      `The employee ${m.firstName} ${m.lastName} is engaged as ${m.position ?? 'Field Technician'}`,
      `by ${org.name}, Arbeiterheimstraße 32, 4663 Laakirchen, commencing 01.09.2026.`,
      '',
      '§2 Working time',
      'Regular weekly working time is 38.5 hours, Monday to Friday.',
      '',
      '§3 Notice',
      'Either party may terminate in accordance with statutory notice periods.',
    ], true);

    const doc = await file({
      user: m, typeId: contract.id, title: `Employment contract — ${m.firstName} ${m.lastName}`,
      bytes, status: i === 0 ? 'SIGNED' : 'AWAITING_SIGNATURE',
      firstOpenedAt: i === 0 ? daysFromNow(-20) : null,
      issuedAt: daysFromNow(-21),
    });

    if (i === 0) {
      // A complete signature record, so the evidence trail has something in it.
      const sigPng = Buffer.concat([
        Buffer.from(
          'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
          'base64',
        ),
        Buffer.alloc(256, 0),
      ]);
      const sigHash = sha256(sigPng);
      await s3.send(new PutObjectCommand({
        Bucket: BUCKET,
        Key: `${org.id}/signatures/${sigHash.slice(0, 2)}/${sigHash}.png`,
        Body: sigPng, ContentType: 'image/png',
      }));
      await prisma.documentSignature.create({
        data: {
          documentId: doc.id, userId: m.id,
          signatureKey: `${org.id}/signatures/${sigHash.slice(0, 2)}/${sigHash}.png`,
          signatureSha256: sigHash,
          consentText: 'I have read this document and agree to sign it electronically.',
          consentAt: daysFromNow(-20), signedAt: daysFromNow(-20),
          hashBefore: doc.sha256, hashAfter: doc.sha256,
          sealedAt: daysFromNow(-20),
          idempotencyKey: `${SEED}${doc.id}`,
        },
      });
      for (const type of ['DELIVERED', 'OPENED', 'CONSENTED', 'SIGNED', 'SEALED'] as const) {
        await prisma.documentEvent.create({
          data: {
            documentId: doc.id, type, actorId: m.id, at: daysFromNow(-20),
            ip: '84.115.20.11', userAgent: 'HBCField/1.0.2 iOS 18.4', appVersion: '1.0.2',
            lat: 47.9813, lng: 13.8269,
          },
        });
      }
    }
  }

  // members[1]'s previous contract: signed last year, superseded by the one
  // now waiting. Gives that account a sealed document to open on a phone.
  if (members[1]) {
    const m = members[1];
    const prior = await file({
      user: m,
      typeId: contract.id,
      title: `Employment contract ${thisYear - 1} — ${m.firstName} ${m.lastName}`,
      status: 'SIGNED',
      issuedAt: new Date(thisYear - 1, 8, 1),
      firstOpenedAt: new Date(thisYear - 1, 8, 2),
      bytes: await makePdf(`Employment contract ${thisYear - 1}`, [
        '§1 Position',
        `The employee ${m.firstName} ${m.lastName} is engaged as ${m.position ?? 'Field Technician'}`,
        `by ${org.name}, Arbeiterheimstraße 32, 4663 Laakirchen, commencing 01.09.${thisYear - 1}.`,
        '',
        '§2 Working time',
        'Regular weekly working time is 38.5 hours, Monday to Friday.',
        '',
        `Superseded by the ${thisYear} agreement.`,
      ], true),
    });

    const sigPng = Buffer.concat([
      Buffer.from(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
        'base64',
      ),
      Buffer.alloc(256, 0),
    ]);
    const sigHash = sha256(sigPng);
    await s3.send(new PutObjectCommand({
      Bucket: BUCKET,
      Key: `${org.id}/signatures/${sigHash.slice(0, 2)}/${sigHash}.png`,
      Body: sigPng, ContentType: 'image/png',
    }));
    await prisma.documentSignature.create({
      data: {
        documentId: prior.id, userId: m.id,
        signatureKey: `${org.id}/signatures/${sigHash.slice(0, 2)}/${sigHash}.png`,
        signatureSha256: sigHash,
        consentText: 'I have read this document and agree to sign it electronically.',
        consentAt: new Date(thisYear - 1, 8, 2), signedAt: new Date(thisYear - 1, 8, 2),
        hashBefore: prior.sha256, hashAfter: prior.sha256,
        sealedAt: new Date(thisYear - 1, 8, 2),
        idempotencyKey: `${SEED}prior_${prior.id}`,
      },
    });
    for (const type of ['DELIVERED', 'OPENED', 'CONSENTED', 'SIGNED', 'SEALED'] as const) {
      await prisma.documentEvent.create({
        data: {
          documentId: prior.id, type, actorId: m.id, at: new Date(thisYear - 1, 8, 2),
          ip: '84.115.20.11', userAgent: 'HBCField/1.0.2 iOS 18.4', appVersion: '1.0.2',
          lat: 47.9813, lng: 13.8269,
        },
      });
    }
  }

  /*
    Everything else that needs a signature or an acknowledgement.

    Spread deliberately unevenly: some people have a queue, some have one, and
    the admin has none outstanding — a demo where everybody has exactly the same
    two documents does not show what the list looks like when it is busy.
  */
  const signables: {
    type: typeof nda;
    title: string;
    lines: string[];
    /** Which members get it, by index. */
    who: number[];
    issuedDaysAgo: number;
  }[] = [
    {
      type: nda,
      title: 'Confidentiality agreement',
      who: [1, 2, 3, 5],
      issuedDaysAgo: 5,
      lines: [
        '§1 Scope',
        'The employee will encounter customer addresses, access codes, pricing and',
        'site details that are confidential to the company and its clients.',
        '',
        '§2 Obligation',
        'This information may not be shared, photographed or retained after the',
        'engagement ends, in any form, including on personal devices.',
        '',
        '§3 Duration',
        'This obligation continues for three years after the engagement ends.',
      ],
    },
    {
      type: equipment,
      title: 'Equipment handover',
      who: [1, 3, 4],
      issuedDaysAgo: 3,
      lines: [
        'Issued to the employee:',
        '  Van                            Ford Transit · W-12345X',
        '  Phone                          iPhone 15 · IMEI 35•••••••••42',
        '  Tool case                      Serial TK-88214',
        '  Fuel card                      •••• 4417',
        '',
        'Condition:',
        '  Checked and photographed at handover. Damage beyond fair wear is',
        '  reported on the day it happens.',
        '',
        'Return:',
        '  All items return on the last working day of the engagement.',
      ],
    },
    {
      type: amendment,
      title: `Contract amendment — working time ${thisYear}`,
      who: [2, 4],
      issuedDaysAgo: 11,
      lines: [
        '§1 Amendment',
        'Regular weekly working time changes from 38.5 to 40.0 hours with effect',
        `from 1 October ${thisYear}.`,
        '',
        '§2 Remuneration',
        'Base salary is adjusted proportionally. All other terms of the original',
        'agreement are unchanged and remain in force.',
      ],
    },
    {
      type: conduct,
      title: `Code of conduct ${thisYear}`,
      who: [1, 2, 3, 4, 5, 6],
      issuedDaysAgo: 14,
      lines: [
        'On site:',
        '  Identify yourself, work to the agreed scope, and leave the site as you',
        '  found it.',
        '',
        'With customers:',
        '  No work is agreed verbally. Anything beyond the order goes back to the',
        '  office before it starts.',
        '',
        'Reporting:',
        '  Anything unsafe, damaged or disputed is reported the same day.',
      ],
    },
    {
      type: privacy,
      title: 'Privacy notice — employee data',
      who: [1, 2, 4, 6],
      issuedDaysAgo: 17,
      lines: [
        'What is held:',
        '  Contact details, contract terms, attendance, location while on a job,',
        '  and the documents in this file.',
        '',
        'Why:',
        '  To pay you, to schedule work, and to meet record-keeping obligations.',
        '',
        'How long:',
        '  Employment records for three years after the engagement ends; payroll',
        '  records for longer, where the law requires it.',
        '',
        'Your rights:',
        '  You can export everything in this file at any time from My documents.',
      ],
    },
    {
      type: fixedTerm,
      title: `Fixed-term contract — seasonal ${thisYear}`,
      who: [2],
      issuedDaysAgo: 8,
      lines: [
        '§1 Term',
        `This engagement runs from 1 November ${thisYear} to 28 February ${thisYear + 1}.`,
        '',
        '§2 Form',
        'A fixed-term agreement must be signed on paper. Please sign the printed',
        'copy and return it to the office — it cannot be signed in the app.',
      ],
    },
  ];

  for (const item of signables) {
    const bytes = await makePdf(item.title, item.lines, true);
    for (const idx of item.who) {
      const m = members[idx];
      if (!m) continue;
      await file({
        user: m,
        typeId: item.type.id,
        title: item.title,
        bytes,
        // WET_INK is issued, not "awaiting" — the app cannot clear it, so
        // leaving it blocking would be a queue item nobody can ever finish.
        status: item.type.signatureMode === 'WET_INK' ? 'ISSUED' : 'AWAITING_SIGNATURE',
        firstOpenedAt: null,
        issuedAt: daysFromNow(-item.issuedDaysAgo),
      });
    }
  }

  // Credentials — one of each standing, so the compliance board has all three.
  const licenceBytes = await makePdf('Driving licence', ['Category B', 'Issued by BH Gmunden'], false);
  const gasBytes = await makePdf('Gas Safe certificate', ['Domestic gas appliances', 'Registration 4471-22'], false);

  const standings: [number, string][] = [
    [+900, 'valid for years'],
    [+24, 'expiring — inside the 60-day window'],
    [-26, 'expired'],
  ];
  for (const [i, m] of members.slice(0, 3).entries()) {
    const [days] = standings[i]!;
    await file({
      user: m, typeId: licence.id, title: 'Driving licence B', bytes: licenceBytes,
      expiresOn: daysFromNow(900), issuedAt: daysFromNow(-400),
    });
    await file({
      user: m, typeId: gasSafe.id, title: 'Gas Safe certificate', bytes: gasBytes,
      expiresOn: daysFromNow(days),
      status: days < 0 ? 'EXPIRED' : 'ISSUED',
      issuedAt: daysFromNow(-500),
    });
  }

  // ── What was built ────────────────────────────────────────────────────────
  console.log(`  ${created} documents (real PDFs, uploaded)\n`);
  console.log('── What to look at ──\n');
  console.log(`  ADMIN  ${admin.email}`);
  console.log('    /my/documents              their OWN file — an admin is an employee too');
  console.log('    /documents                 issue a batch');
  console.log('    /documents/templates       the contract template');
  console.log('    /documents/compliance      1 valid · 1 expiring · 1 expired');
  // members[0] is the admin, already listed above. A one-person organization
  // has nobody else, and the summary must not crash on that.
  if (members[1]) {
    console.log(`\n  MEMBER ${members[1].email}   (password123)`);
    console.log('    /my/documents              payslips, contract SIGNED, policy read');
  }
  if (members[2]) {
    console.log(`\n  MEMBER ${members[2].email}   (password123)`);
    console.log('    /my/documents              a contract AWAITING SIGNATURE — sign it');
  }
  console.log('    mobile: Profile → Documents\n');
}

/**
 * `--all` fills EVERY organization that has users.
 *
 * On a developer database there are a dozen organizations from old experiments,
 * and "which one am I actually logged into?" is not a question anybody should
 * have to answer before they can see whether a feature works. Filling all of
 * them costs a few seconds and removes the question.
 */
async function seedEverything() {
  const orgs = await prisma.organization.findMany({
    where: { users: { some: { role: 'ADMIN' } } },
    include: { _count: { select: { users: true } } },
  });
  const ordered = orgs.sort((a, b) => b._count.users - a._count.users);
  console.log(`\n── Filling ${ordered.length} organizations ──`);

  for (const o of ordered) {
    const admin = await prisma.user.findFirst({
      where: { organizationId: o.id, role: 'ADMIN' },
      select: { email: true },
    });
    if (!admin) continue;
    try {
      process.argv[2] = admin.email;
      await main();
    } catch (e) {
      console.error(`  ${o.name}: ${(e as Error).message}`);
    }
  }
}

const runner = process.argv[2] === '--all' ? seedEverything() : main();
runner
  .catch((e) => { console.error('\nSeed failed:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
